accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include  # NOQA
from django.urls import path

from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path(
        "login", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>", accounts_views.delete_user, name="delete_user"),
    path("users", accounts_views.user_list, name="user_list"),
    path("adduser", accounts_views.add_user, name="add_user"),
    path(
        "remove_user_service/<int:service_pk>/<int:user_pk>/",
        accounts_views.remove_user_service,
        name="remove_user_service",
    ),
    path(
        "service_users/<int:service_pk>/",
        accounts_views.service_users,
        name="service_users",
    ),
    path(
        "add_user_service/<int:service_pk>/",
        accounts_views.add_user_in_service,
        name="add_user_in_service",
    ),
    path("edit_user/<int:pk>/", accounts_views.edit_user, name="edit_user"),
    path("my_account", accounts_views.my_account, name="my_account"),
    path("change_password", accounts_views.change_password, name="change_password"),
    path("view_plugin/<str:plugin>", accounts_views.view_plugin, name="view_plugin"),
    path("plugin_list", accounts_views.plugin_list, name="plugin_list"),
    # Plugin URL example
    # path(
    #     "plugin/generic_plugin",
    #     include("sc_generic_plugin.urls", namespace="generic_plugin"),
    # ),
]

checker/urls.py
from django.urls import include
from django.urls import path

from checker import views
from checker.views import Pdf

# app_name = 'checker'

urlpatterns = [
    path("", views.home, name="home"),
    path("ping/<int:pk>/", views.ping_info, name="ping_info"),
    path("users", views.user_list, name="user_list"),
    path("adduser", views.add_user, name="add_user"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("add_site", views.add_site, name="add_site"),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
    path("maintenance/<int:pk>", views.maintenance, name="maintenance"),
    path(
        "remove_user/<int:site_pk>/<int:user_pk>", views.remove_user, name="remove_user"
    ),
    path("edit_site/<int:pk>", views.edit_site, name="edit_site"),
    path("edit_user/<int:pk>", views.edit_user, name="edit_user"),
    path("delete_site/<int:pk>", views.delete_site, name="delete_site"),
    path("delete_user/<int:pk>", views.delete_user, name="delete_user"),
]

sitechecker/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("checkerapp.urls", namespace="checker")),
]

templates/plugins/email.html
{% extends 'base_accounts.html' %}

{% block head %}
<title>My Account</title>
{% endblock head %}


{% block breadcrumb %}
<li class="breadcrumb-item active">My Account</li>
<li class="breadcrumb-item active">Alert Plugins</li>
<li class="breadcrumb-item text-primary">Email Plugin</li>
{% endblock %}

{% block sidenav %}
  <a href="{% url 'accounts:my_account' %}" class="list-group-item list-group-item-action bg-light">Account Settings</a>
  <a href="{% url 'accounts:change_password' %}" class="list-group-item list-group-item-action bg-light">Change Password</a>
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">Email Plugin</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            Email : <input type='text' class="form-control" name='email' placeholder='email' value="{{request.user.email}}">
            <small class="font-italic text-secondary">*Email alerts cannot be disabled</small>
            <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/plugins/plugin.html
{% extends 'base_accounts.html' %}

{% block head %}
<title>My Account</title>
{% endblock head %}


{% block breadcrumb %}
<li class="breadcrumb-item active">My Account</li>
<li class="breadcrumb-item active">Alert Plugins</li>
<li class="breadcrumb-item text-primary">{{plugin_name}}</li>
{% endblock %}

{% block sidenav %}
  <a href="{% url 'accounts:my_account' %}" class="list-group-item list-group-item-action bg-light">Account Settings</a>
  <a href="{% url 'accounts:change_password' %}" class="list-group-item list-group-item-action bg-light">Change Password</a>
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">{{plugin_name}}</h3>
          <form method="post" novalidate>
            {% csrf_token %}
              {{form}}
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/plugins/plugin_list.html
{% extends 'base_accounts.html' %}

{% block head %}
<title>Plugin List</title>
{% endblock head %}


{% block breadcrumb %}
<li class="breadcrumb-item active">My Account</li>
<li class="breadcrumb-item text-primary">Plugin List</li>
{% endblock %}

{% block sidenav %}
  <a href="{% url 'accounts:my_account' %}" class="list-group-item list-group-item-action bg-light">Account Settings</a>
  <a href="{% url 'accounts:change_password' %}" class=" text-dark list-group-item list-group-item-action bg-white">Change Password</a>
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">Custom Plugin List</h3>
          {% for plugin_name, plugin_obj in plugin_data %}
            {% comment %} <a href="{% url 'accounts:view_plugin' plugins_obj.url %}"><p>{{plugin}}</p></a> {% endcomment %}
            <a href="{% url plugin_obj.url %}"><p>{{plugin_name}}</p></a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/plugins/sms.html
{% extends 'base_accounts.html' %}

{% block head %}
<title>My Account</title>
{% endblock head %}


{% block breadcrumb %}
<li class="breadcrumb-item active">My Account</li>
<li class="breadcrumb-item active">Alert Plugins</li>
<li class="breadcrumb-item text-primary">SMS Plugin</li>
{% endblock %}

{% block sidenav %}
  <a href="{% url 'accounts:my_account' %}" class="list-group-item list-group-item-action bg-light">Account Settings</a>
  <a href="{% url 'accounts:change_password' %}" class="list-group-item list-group-item-action bg-light">Change Password</a>
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">SMS Plugin</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            Phone number : <input type='text' class="form-control" name='phone_number' placeholder='phone number' value="{{request.user.profile.phone}}">
            <div class="form-check mt-3">
              <input name="active_status" type="checkbox" class="form-check-input" {% if request.user.profile.active_status %}checked{% endif %}>
              <label class="form-check-label">Active Status</label>
            </div>
            <small class="font-italic text-secondary">*Disabling Active Status would disable all alerts related to profile table</small>
            <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}