checker/urls.py
from django.urls import include
from django.urls import path

from checker import views
from checker.views import Pdf

# app_name = 'checker'

urlpatterns = [
    path("", views.home, name="home"),
    path("ping/<int:pk>/", views.ping_info, name="ping_info"),
    path("users", views.user_list, name="user_list"),
    path("adduser", views.add_user, name="add_user"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("add_site", views.add_site, name="add_site"),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
    path("maintenance/<int:pk>", views.maintenance, name="maintenance"),
    path(
        "remove_user/<int:site_pk>/<int:user_pk>", views.remove_user, name="remove_user"
    ),
    path("edit_site/<int:pk>", views.edit_site, name="edit_site"),
    path("edit_user/<int:pk>", views.edit_user, name="edit_user"),
    path("delete_site/<int:pk>", views.delete_site, name="delete_site"),
    path("delete_user/<int:pk>", views.delete_user, name="delete_user"),
]

checkerapp/urls.py
from django.urls import path

from checkerapp import views
from checkerapp.views import Pdf

app_name = "checkerapp"

urlpatterns = [
    path("", views.home, name="home"),
    path("add_service", views.add_service, name="add_service"),
    path("edit_service/<int:service_pk>/", views.edit_service, name="edit_service"),
    path(
        "delete_service/<int:service_pk>/", views.delete_service, name="delete_service"
    ),
    path("service/<int:pk>/", views.service, name="service"),
    path("service/http_info/<int:pk>/", views.http_info, name="http_info"),
    path("service/ping_info/<int:pk>/", views.ping_info, name="ping_info"),
    path("service/tcp_info/<int:pk>/", views.tcp_info, name="tcp_info"),
    path(
        "service/<int:service_pk>/add_http_check/",
        views.add_http_check,
        name="add_http_check",
    ),
    path(
        "service/<int:service_pk>/add_ping_check/",
        views.add_ping_check,
        name="add_ping_check",
    ),
    path(
        "service/<int:service_pk>/add_tcp_check/",
        views.add_tcp_check,
        name="add_tcp_check",
    ),
    path(
        "service/<int:service_pk>/edit_http_check/<int:http_pk>/",
        views.edit_http_check,
        name="edit_http_check",
    ),
    path(
        "service/<int:service_pk>/edit_ping_check/<int:ping_pk>/",
        views.edit_ping_check,
        name="edit_ping_check",
    ),
    path(
        "service/<int:service_pk>/edit_tcp_check/<int:tcp_pk>/",
        views.edit_tcp_check,
        name="edit_tcp_check",
    ),
    path(
        "maintenance/<int:service_type_id>/<int:service_pk>/<int:pk>/",
        views.maintenance,
        name="maintenance",
    ),
    path(
        "delete_check/<int:service_type_id>/<int:service_pk>/<int:pk>/",
        views.delete_check,
        name="delete_check",
    ),
    path(
        "delete_critical_plugin/<int:service_pk>/<int:plugin_pk>/",
        views.delete_critical_plugin,
        name="delete_critical_plugin",
    ),
    path(
        "delete_warning_plugin/<int:service_pk>/<int:plugin_pk>/",
        views.delete_warning_plugin,
        name="delete_warning_plugin",
    ),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
]

sitechecker/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("checkerapp.urls", namespace="checker")),
]

checkerapp/models.py
import logging

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from polymorphic.models import PolymorphicModel

logger = logging.getLogger(__name__)


class BaseCheck(models.Model):
    WARNING, CRITICAL = list(range(2))
    SEVERE_CHOICES = ((WARNING, "WARNING"), (CRITICAL, "CRITICAL"))

    interval = models.IntegerField(default=1)
    backoff_count = models.IntegerField(default=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    severe_level = models.SmallIntegerField(choices=SEVERE_CHOICES, default=0)
    creator = models.ForeignKey(
        User, related_name="commoninfo_creator", on_delete=models.CASCADE
    )
    maintenance_mode = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=50)
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return f"{self.content_object}"


class AlertPlugin(PolymorphicModel):
    active_status = models.BooleanField(default=True)
    alert_receiver = models.ForeignKey(
        User, related_name="alert_receiver", on_delete=models.CASCADE
    )


class PluginList(models.Model):
    name = models.CharField(max_length=50)
    active_status = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"


class Service(models.Model):
    warning_severity = models.ManyToManyField(
        PluginList, related_name="warnign_plugin_list"
    )
    critical_severity = models.ManyToManyField(
        PluginList, related_name="critical_plugin_list"
    )

    name = models.CharField(max_length=50, unique=True)
    users = models.ManyToManyField(User, related_name="service_users")
    checks = models.ManyToManyField(BaseCheck)


class CheckResult(models.Model):
    FAILURE, SUCCESS = list(range(2))
    RESULT_CHOICES = ((SUCCESS, "SUCCESS"), (FAILURE, "FAILURE"))

    result = models.SmallIntegerField(choices=RESULT_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)


class AlertSent(models.Model):
    check_obj = models.ForeignKey(BaseCheck, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)


class AbstractCheck(models.Model):
    base_check = GenericRelation(BaseCheck)
    results = models.ManyToManyField(CheckResult)

    class Meta:
        abstract = True

    @staticmethod
    def execute():
        raise NotImplementedError()


class HttpCheck(AbstractCheck):
    site_name = models.CharField(max_length=50, unique=True, default="https://")
    expected_status_code = models.IntegerField()

    def __str__(self):
        return f"{self.site_name}"

    @staticmethod
    def execute():
        pass


class PingCheck(AbstractCheck):
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return f"{self.ip_address}"

    @staticmethod
    def execute():
        pass


class TcpCheck(AbstractCheck):
    ip_address = models.GenericIPAddressField()
    port = models.IntegerField(default=443)

    def __str__(self):
        return f"{self.ip_address}"

    @staticmethod
    def execute():
        pass

templates/check_info/http_info.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<title>Http Info</title>

{% endblock head %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:home' %}">Services</a></li>
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:service' base_check.service_set.first.id %}">{{base_check.service_set.first.name}}</a></li>
    <li class="breadcrumb-item active">{{site.site_name}}</li>
{% endblock %}

{% block body %}
    <div class="container">
      <div class="row col-12">
       <div class='row col-5'>
          <img src='{% static "images/down_time.png" %}' class='mr-2' width=30 height=30/>
          {% if last_down_time%}
            <p>Last Down Time : {{last_down_time.created_at}}</p>
            {% else %}
            <p>Last Down Time : No down time</p>
            {% endif %}
        <div class='row ml-1'>
          <img src='{% static "images/severe_level.png" %}' class='mr-2' width=30 height=30/>
          <p>Severe Level : {{base_check.get_severe_level_display}}</p>
        </div>
       </div>
      </div>
  <div class="row">
      <table class="table jumbotron col-6 shadow-sm">
        <thead class="thead-inverse">
          <tr>
            <th>Status</th>
            <th>Time</th>
          </tr>
        </thead>
        {% if result %}
        <tbody>
          {% for status in result %}
            <tr>
              <td class="align-middle">{{status.get_result_display}}</td>
              <td class="align-middle">{{status.created_at}}</td>
            </tr>
          {% endfor %}
        </tbody>
        {% else %}
        <tbody>
          <tr><td>No checks</td></tr>
        </tbody>
        {% endif %}
      </table>
      <div class="col-1 "></div>
      </div>

  {% if result.has_other_pages %}
    <ul class="pagination">
      {% if result.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ result.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span></span></li>
      {% endif %}

      {% for i in result.paginator.page_range %}
        {% if i <= result.number|add:5 and i >= result.number|add:-5 %}
          {% if result.number == i %}
            <li class="page-item active page-link"><span>{{ i }} <span class="sr-only page-link">(current)</span></span></li>
          {% else %}
            <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if result.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ result.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span></span></li>
      {% endif %}
    </ul>
  {% endif %}


      </div>
 </body>
{% endblock body %}

templates/check_info/ping_info.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<title>Ping Info</title>

{% endblock head %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:home' %}">Services</a></li>
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:service' base_check.service_set.first.id %}">{{base_check.service_set.first.name}}</a></li>
    <li class="breadcrumb-item active">{{ip_address.ip_address}}</li>
{% endblock %}
{% block body %}
    <div class="container">
      <div class="row col-12">
      <div class='row col-5'>
          <img src='{% static "images/down_time.png" %}' class='mr-2' width=30 height=30/>
          {% if last_down_time%}
            <p>Last Down Time : {{last_down_time.created_at}}</p>
            {% else %}
            <p>Last Down Time : No down time</p>
            {% endif %}
        <div class='row ml-1'>
          <img src='{% static "images/severe_level.png" %}' class='mr-2' width=30 height=30/>
          <p>Severe Level : {{base_check.get_severe_level_display}}</p>
        </div>
       </div>

      </div>
      <div class="row">
      <table class="table jumbotron col-6 shadow-sm">
        <thead class="thead-inverse">
          <tr>
            <th>Status</th>
            <th>Time</th>
          </tr>
        </thead>
        {% if result %}
        <tbody>
          {% for status in result %}
            <tr>
              <td class="align-middle">{{status.get_result_display}}</td>
              <td class="align-middle">{{status.created_at}}</td>
            </tr>
          {% endfor %}
        </tbody>
        {% else %}
        <tbody>
          <tr><td>No checks</td></tr>
        </tbody>
        {% endif %}
      </table>
      <div class="col-1 "></div>
      </div>

{% if result.has_other_pages %}
  <ul class="pagination">
    {% if result.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ result.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span></span></li>
    {% endif %}

    {% for i in result.paginator.page_range %}
      {% if i <= result.number|add:5 and i >= result.number|add:-5 %}
        {% if result.number == i %}
          <li class="page-item active page-link"><span>{{ i }} <span class="sr-only page-link">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endif %}
    {% endfor %}

    {% if result.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ result.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span></span></li>
    {% endif %}
  </ul>
{% endif %}
    </div>
 </body>
{% endblock body %}

templates/check_info/tcp_info.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<title>TCP Info</title>

{% endblock head %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:home' %}">Services</a></li>
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:service' base_check.service_set.first.id %}">{{base_check.service_set.first.name}}</a></li>
    <li class="breadcrumb-item active">{{ip_address.ip_address}}</li>
{% endblock %}

{% block body %}
    <div class="container">
      <div class="row col-12">
      <div class='row col-5'>
          <img src='{% static "images/down_time.png" %}' class='mr-2' width=30 height=30/>
          {% if last_down_time%}
            <p>Last Down Time : {{last_down_time.created_at}}</p>
            {% else %}
            <p>Last Down Time : No down time</p>
            {% endif %}
        <div class='row ml-1'>
          <img src='{% static "images/severe_level.png" %}' class='mr-2' width=30 height=30/>
          <p>Severe Level : {{base_check.get_severe_level_display}}</p>
        </div>
       </div>

      </div>
      <div class="row">
      <table class="table jumbotron col-6 shadow-sm">
        <thead class="thead-inverse">
          <tr>
            <th>Status</th>
            <th>Time</th>
          </tr>
        </thead>
        {% if result %}
        <tbody>
          {% for status in result %}
            <tr>
              <td class="align-middle">{{status.get_result_display}}</td>
              <td class="align-middle">{{status.created_at}}</td>
            </tr>
          {% endfor %}
        </tbody>
        {% else %}
        <tbody>
          <tr><td>No checks</td></tr>
        </tbody>
        {% endif %}
      </table>
      <div class="col-1 "></div>
      </div>

{% if result.has_other_pages %}
  <ul class="pagination">
    {% if result.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ result.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span></span></li>
    {% endif %}

    {% for i in result.paginator.page_range %}
      {% if i <= result.number|add:5 and i >= result.number|add:-5 %}
        {% if result.number == i %}
          <li class="page-item active page-link"><span>{{ i }} <span class="sr-only page-link">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endif %}
    {% endfor %}

    {% if result.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ result.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span></span></li>
    {% endif %}
  </ul>
{% endif %}
    </div>
 </body>
{% endblock body %}