accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include  # NOQA
from django.urls import path

from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path(
        "login", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>", accounts_views.delete_user, name="delete_user"),
    path("users", accounts_views.user_list, name="user_list"),
    path("adduser", accounts_views.add_user, name="add_user"),
    path(
        "remove_user_service/<int:service_pk>/<int:user_pk>/",
        accounts_views.remove_user_service,
        name="remove_user_service",
    ),
    path(
        "service_users/<int:service_pk>/",
        accounts_views.service_users,
        name="service_users",
    ),
    path(
        "add_user_service/<int:service_pk>/",
        accounts_views.add_user_in_service,
        name="add_user_in_service",
    ),
    path("edit_user/<int:pk>/", accounts_views.edit_user, name="edit_user"),
    path("my_account", accounts_views.my_account, name="my_account"),
    path("change_password", accounts_views.change_password, name="change_password"),
    path("view_plugin/<str:plugin>", accounts_views.view_plugin, name="view_plugin"),
    path("plugin_list", accounts_views.plugin_list, name="plugin_list"),
    # Plugin URL example
    # path(
    #     "plugin/generic_plugin",
    #     include("sc_generic_plugin.urls", namespace="generic_plugin"),
    # ),
]

checker/urls.py
from django.urls import include
from django.urls import path

from checker import views
from checker.views import Pdf

# app_name = 'checker'

urlpatterns = [
    path("", views.home, name="home"),
    path("ping/<int:pk>/", views.ping_info, name="ping_info"),
    path("users", views.user_list, name="user_list"),
    path("adduser", views.add_user, name="add_user"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("add_site", views.add_site, name="add_site"),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
    path("maintenance/<int:pk>", views.maintenance, name="maintenance"),
    path(
        "remove_user/<int:site_pk>/<int:user_pk>", views.remove_user, name="remove_user"
    ),
    path("edit_site/<int:pk>", views.edit_site, name="edit_site"),
    path("edit_user/<int:pk>", views.edit_user, name="edit_user"),
    path("delete_site/<int:pk>", views.delete_site, name="delete_site"),
    path("delete_user/<int:pk>", views.delete_user, name="delete_user"),
]

checkerapp/urls.py
from django.urls import path

from checkerapp import views
from checkerapp.views import Pdf

app_name = "checkerapp"

urlpatterns = [
    path("", views.home, name="home"),
    path("add_service", views.add_service, name="add_service"),
    path("edit_service/<int:service_pk>/", views.edit_service, name="edit_service"),
    path(
        "delete_service/<int:service_pk>/", views.delete_service, name="delete_service"
    ),
    path("service/<int:pk>/", views.service, name="service"),
    path("service/http_info/<int:pk>/", views.http_info, name="http_info"),
    path("service/ping_info/<int:pk>/", views.ping_info, name="ping_info"),
    path("service/tcp_info/<int:pk>/", views.tcp_info, name="tcp_info"),
    path(
        "service/<int:service_pk>/add_http_check/",
        views.add_http_check,
        name="add_http_check",
    ),
    path(
        "service/<int:service_pk>/add_ping_check/",
        views.add_ping_check,
        name="add_ping_check",
    ),
    path(
        "service/<int:service_pk>/add_tcp_check/",
        views.add_tcp_check,
        name="add_tcp_check",
    ),
    path(
        "service/<int:service_pk>/edit_http_check/<int:http_pk>/",
        views.edit_http_check,
        name="edit_http_check",
    ),
    path(
        "service/<int:service_pk>/edit_ping_check/<int:ping_pk>/",
        views.edit_ping_check,
        name="edit_ping_check",
    ),
    path(
        "service/<int:service_pk>/edit_tcp_check/<int:tcp_pk>/",
        views.edit_tcp_check,
        name="edit_tcp_check",
    ),
    path(
        "maintenance/<int:service_type_id>/<int:service_pk>/<int:pk>/",
        views.maintenance,
        name="maintenance",
    ),
    path(
        "delete_check/<int:service_type_id>/<int:service_pk>/<int:pk>/",
        views.delete_check,
        name="delete_check",
    ),
    path(
        "delete_critical_plugin/<int:service_pk>/<int:plugin_pk>/",
        views.delete_critical_plugin,
        name="delete_critical_plugin",
    ),
    path(
        "delete_warning_plugin/<int:service_pk>/<int:plugin_pk>/",
        views.delete_warning_plugin,
        name="delete_warning_plugin",
    ),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
]

sitechecker/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("checkerapp.urls", namespace="checker")),
]

accounts/models.py
from django.db import models  # NOQA

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"class": "form-control", "type": "password"}),
        required=True,
    )

    confirm_password = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"class": "form-control", "type": "password"}),
        required=True,
    )

    class Meta:
        model = User
        fields = ("username", "email", "password", "confirm_password")


class MyAccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username")


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email")


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Username", widget=forms.TextInput(attrs={"class": "form-control"})
    )
    password = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"class": "form-control", "type": "password"}),
        required=True,
    )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.shortcuts import render

from .forms import EditUserForm
from .forms import MyAccountForm
from .forms import UserForm
from checkerapp.models import AlertPlugin
from checkerapp.models import Service


@login_required
def delete_user(request, pk):
    user_to_delete = User.objects.get(id=pk)
    user_to_delete.delete()
    messages.success(request, f" {user_to_delete.username} deleted from user list !!")
    return redirect("accounts:user_list")


@login_required
def edit_user(request, pk):
    if not request.user.is_superuser:
        return redirect("checkerapp:home")
    user_info = User.objects.get(id=pk)

    form = EditUserForm(request.POST or None, instance=user_info)
    if form.is_valid():
        form.save()
        messages.success(request, f"Account info updated ! !")
        return redirect("accounts:user_list")

    context = {"form": form}
    return render(request, "edit_user.html", context)


@login_required
def user_list(request):
    if not request.user.is_superuser:
        return redirect("checkerapp:home")
    list_of_users = User.objects.filter(is_superuser=False).order_by("id")
    return render(request, "user_list.html", context={"users": list_of_users})


@login_required
def add_user(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            email = user_form.cleaned_data.get("email")
            username = user_form.cleaned_data.get("username")
            password = user_form.cleaned_data.get("password")
            user = User.objects.create_user(
                email=email, username=username, password=password
            )
            user.save()
            messages.success(request, f"{user.username} added to users list !")
            return redirect("accounts:user_list")

    context = {"form": UserForm()}
    return render(request, "add_user.html", context)


@login_required
def add_user_in_service(request, service_pk):
    selected_users = request.POST.getlist("listxblocks")
    service_obj = Service.objects.get(id=service_pk)
    for user in selected_users:
        service_obj.users.add(user)
    return redirect("accounts:service_users", service_pk=service_pk)


@login_required
def remove_user_service(request, service_pk, user_pk):
    user = User.objects.get(id=user_pk)
    service_obj = Service.objects.get(id=service_pk)
    service_obj.users.remove(user)
    messages.success(request, f"{user.username} removed from {service_obj.name} !")
    return redirect("accounts:service_users", service_pk=service_pk)


@login_required
def service_users(request, service_pk):
    service_obj = Service.objects.get(id=service_pk)
    service_users = service_obj.users.all()
    all_users = User.objects.all()
    context = {"users": service_users, "all_users": all_users, "service": service_obj}
    return render(request, "service_users.html", context)


@login_required
def my_account(request):
    user_info = User.objects.get(id=request.user.pk)
    if user_info:
        form = MyAccountForm(request.POST or None, instance=user_info)
    else:
        form = MyAccountForm()
    if form.is_valid():
        form.save()
        messages.success(request, f"Account info updated ! !")
        return redirect("accounts:my_account")

    context = {"form": form}
    return render(request, "my_account.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, f"Password Changed !")
            return redirect("checkerapp:home")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    context = {"form": PasswordChangeForm(request.user)}
    return render(request, "change_pass.html", context)


@login_required
def plugin_list(request):
    plugins_name = [cls.__name__ for cls in AlertPlugin.__subclasses__()]
    plugins_obj = [cls for cls in AlertPlugin.__subclasses__()]

    context = {}
    context["plugin_data"] = zip(plugins_name, plugins_obj)
    return render(request, "plugins/plugin_list.html", context)


@login_required
def view_plugin(request, plugin):
    plugin_obj = plugin()
    return redirect(plugin_obj.url)

accounts/templates/add_user.html
{% extends 'base.html' %}

{% block head %}
<title>
Add user to notify
</title>
{% endblock %}
x
{% block breadcrumb %}
<li class="breadcrumb-item active">Add User</li>
{% endblock %}

{% block body %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <div class="card shadow-sm">
        <div class="card-body">
          <h3 class="card-title">Add user</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block mt-2">Add user</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/base_accounts.html
{% extends 'base.html' %}
{% load static %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
  <link rel="stylesheet" href="https://raw.githubusercontent.com/StartBootstrap/startbootstrap-simple-sidebar/master/css/simple-sidebar.css">

{% endblock %}

{% block body %}
<div class="container">
  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="list-group list-group-flush">
      {% block sidenav %}

      {% endblock %}
      <a href="{% url 'accounts:plugin_list' %}" class="list-group-item list-group-item-action bg-light">Alert plugins</a>
      </div>
    </div>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  </div>
{% endblock %}

accounts/templates/change_pass.html
{% extends 'base_accounts.html' %}

{% block title %}Change Password{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">Change Password</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block mt-2">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/edit_user.html
{% extends 'base.html' %}

{% block head %}
<title>
Edit user
</title>
{% endblock %}
x
{% block breadcrumb %}
<li class="breadcrumb-item active">Edit User</li>
{% endblock %}

{% block body %}
  <div class="row justify-content-center">
    <div class="col-lg-6   col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">Edit user</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block mt-2">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block head %}
<title>
Login to Site Checker
</title>
{% endblock %}
x
{% block breadcrumb %}
<li class="breadcrumb-item active">Login</li>
{% endblock %}

{% block body %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/my_account.html
{% extends 'base_accounts.html' %}

{% block head %}
<title>My Account</title>
{% endblock head %}


{% block breadcrumb %}
<li class="breadcrumb-item active">My Account</li>
<li class="breadcrumb-item text-primary">Account Settings</li>
{% endblock %}

{% block sidenav %}
  <a href="#" class="text-dark list-group-item list-group-item-action bg-white">Account Settings</a>
  <a href="{% url 'accounts:change_password' %}" class="list-group-item list-group-item-action bg-light">Change Password</a>
{% endblock %}



{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title">General</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block mt-2">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/service_users.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Service users</title>
<style>
th, td, h3 {
    text-align: center;
}
</style>
{% endblock head %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'checkerapp:home' %}">Services</a></li>
  <li class="breadcrumb-item active">{{ service.name }} Users</li>
{% endblock %}

{% block body %}
<div class="container mb-3">
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-8 col-sm-4">
      <div class="card">
        <div class="card-body shadow-sm">
          {% comment %} <h3 class="card-title text-center"><a href="{% url 'accounts:add_user' %}">Add user</a></h3> {% endcomment %}

            <form method='POST' action="{% url 'accounts:add_user_in_service' service.pk %}">
              {% csrf_token %}

              <select class="selectpicker" name="listxblocks" multiple data-live-search="true">
              {% if not request.user.is_superuser %}
                <option>Only admin can add</option>
              {% else %}
                {% for add_user in all_users %}
                  {% if add_user not in users %}
                    <option value="{{add_user.id}}">{{add_user.username}}</option>
                  {% endif %}
                {% endfor %}
              {% endif %}
              </select>

              {% if request.user.is_superuser %}
                <button type="submit" class="btn btn-primary m-2 float-right">Add users</button>
              {% endif %}
            </form>

          <table class="table" style="margin:auto">
            <thead class="thead-inverse">
                <tr>
                    <th class="justify-content-center">PK</th>
                    <th class="justify-content-center">Username</th>

                    <th class="justify-content-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                    <td class="align-middle">{{user.pk}}</td>
                    <td class="align-middle">{{user.username}}</td>
                    {% if request.user.is_superuser %}
                      <td>
                          <a href="{% url 'accounts:edit_user' user.pk %}">
                          <img src='{% static "images/edit.png" %}' width=20 height=20/>
                          </a>
                          <a href="{% url 'accounts:remove_user_service' service.pk user.pk %}">
                          <img src='{% static "images/delete.png" %}' width=20 height=20/>
                          </a>
                      </td>
                    {% else %}
                      <td><img class="disabled" src='{% static "images/not_allowed.png" %}' width=20 height=20/></td>
                    {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User List{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">User List</li>
{% endblock %}

{% block body %}
<div class="container mb-3">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-4">
      <div class="card">
        <div class="card-body shadow-sm">
          <h3 class="card-title text-center"><a href="{% url 'accounts:add_user' %}">Add user</a></h3>
          <table class="table" style="margin:auto">
            <thead class="thead-inverse">
                <tr>
                    <th class="justify-content-center">PK</th>
                    <th class="justify-content-center">Username</th>

                    <th class="justify-content-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                    <td class="align-middle">{{user.pk}}</td>
                    <td class="align-middle">{{user.username}}</td>
                    <td>
                        <a href="{% url 'accounts:edit_user' user.pk %}">
                        <img src='{% static "images/edit.png" %}' width=20 height=20/>
                        </a>
                        <a href="{% url 'accounts:delete_user' user.pk %}">
                        <img src='{% static "images/delete.png" %}' width=20 height=20/>
                        </a>
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}