accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include  # NOQA
from django.urls import path

from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path(
        "login", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>", accounts_views.delete_user, name="delete_user"),
    path("users", accounts_views.user_list, name="user_list"),
    path("adduser", accounts_views.add_user, name="add_user"),
    path(
        "remove_user_service/<int:service_pk>/<int:user_pk>/",
        accounts_views.remove_user_service,
        name="remove_user_service",
    ),
    path(
        "service_users/<int:service_pk>/",
        accounts_views.service_users,
        name="service_users",
    ),
    path(
        "add_user_service/<int:service_pk>/",
        accounts_views.add_user_in_service,
        name="add_user_in_service",
    ),
    path("edit_user/<int:pk>/", accounts_views.edit_user, name="edit_user"),
    path("my_account", accounts_views.my_account, name="my_account"),
    path("change_password", accounts_views.change_password, name="change_password"),
    path("view_plugin/<str:plugin>", accounts_views.view_plugin, name="view_plugin"),
    path("plugin_list", accounts_views.plugin_list, name="plugin_list"),
    # Plugin URL example
    # path(
    #     "plugin/generic_plugin",
    #     include("sc_generic_plugin.urls", namespace="generic_plugin"),
    # ),
]

checker/urls.py
from django.urls import include
from django.urls import path

from checker import views
from checker.views import Pdf

# app_name = 'checker'

urlpatterns = [
    path("", views.home, name="home"),
    path("ping/<int:pk>/", views.ping_info, name="ping_info"),
    path("users", views.user_list, name="user_list"),
    path("adduser", views.add_user, name="add_user"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("add_site", views.add_site, name="add_site"),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
    path("maintenance/<int:pk>", views.maintenance, name="maintenance"),
    path(
        "remove_user/<int:site_pk>/<int:user_pk>", views.remove_user, name="remove_user"
    ),
    path("edit_site/<int:pk>", views.edit_site, name="edit_site"),
    path("edit_user/<int:pk>", views.edit_user, name="edit_user"),
    path("delete_site/<int:pk>", views.delete_site, name="delete_site"),
    path("delete_user/<int:pk>", views.delete_user, name="delete_user"),
]

checkerapp/urls.py
from django.urls import path

from checkerapp import views
from checkerapp.views import Pdf

app_name = "checkerapp"

urlpatterns = [
    path("", views.home, name="home"),
    path("add_service", views.add_service, name="add_service"),
    path("edit_service/<int:service_pk>/", views.edit_service, name="edit_service"),
    path(
        "delete_service/<int:service_pk>/", views.delete_service, name="delete_service"
    ),
    path("service/<int:pk>/", views.service, name="service"),
    path("service/http_info/<int:pk>/", views.http_info, name="http_info"),
    path("service/ping_info/<int:pk>/", views.ping_info, name="ping_info"),
    path("service/tcp_info/<int:pk>/", views.tcp_info, name="tcp_info"),
    path(
        "service/<int:service_pk>/add_http_check/",
        views.add_http_check,
        name="add_http_check",
    ),
    path(
        "service/<int:service_pk>/add_ping_check/",
        views.add_ping_check,
        name="add_ping_check",
    ),
    path(
        "service/<int:service_pk>/add_tcp_check/",
        views.add_tcp_check,
        name="add_tcp_check",
    ),
    path(
        "service/<int:service_pk>/edit_http_check/<int:http_pk>/",
        views.edit_http_check,
        name="edit_http_check",
    ),
    path(
        "service/<int:service_pk>/edit_ping_check/<int:ping_pk>/",
        views.edit_ping_check,
        name="edit_ping_check",
    ),
    path(
        "service/<int:service_pk>/edit_tcp_check/<int:tcp_pk>/",
        views.edit_tcp_check,
        name="edit_tcp_check",
    ),
    path(
        "maintenance/<int:service_type_id>/<int:service_pk>/<int:pk>/",
        views.maintenance,
        name="maintenance",
    ),
    path(
        "delete_check/<int:service_type_id>/<int:service_pk>/<int:pk>/",
        views.delete_check,
        name="delete_check",
    ),
    path(
        "delete_critical_plugin/<int:service_pk>/<int:plugin_pk>/",
        views.delete_critical_plugin,
        name="delete_critical_plugin",
    ),
    path(
        "delete_warning_plugin/<int:service_pk>/<int:plugin_pk>/",
        views.delete_warning_plugin,
        name="delete_warning_plugin",
    ),
    path("report/<int:pk>", Pdf.as_view(), name="report"),
]

sitechecker/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("checkerapp.urls", namespace="checker")),
]

checkerapp/models.py
import logging

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from polymorphic.models import PolymorphicModel

logger = logging.getLogger(__name__)


class BaseCheck(models.Model):
    WARNING, CRITICAL = list(range(2))
    SEVERE_CHOICES = ((WARNING, "WARNING"), (CRITICAL, "CRITICAL"))

    interval = models.IntegerField(default=1)
    backoff_count = models.IntegerField(default=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    severe_level = models.SmallIntegerField(choices=SEVERE_CHOICES, default=0)
    creator = models.ForeignKey(
        User, related_name="commoninfo_creator", on_delete=models.CASCADE
    )
    maintenance_mode = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=50)
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return f"{self.content_object}"


class AlertPlugin(PolymorphicModel):
    active_status = models.BooleanField(default=True)
    alert_receiver = models.ForeignKey(
        User, related_name="alert_receiver", on_delete=models.CASCADE
    )


class PluginList(models.Model):
    name = models.CharField(max_length=50)
    active_status = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"


class Service(models.Model):
    warning_severity = models.ManyToManyField(
        PluginList, related_name="warnign_plugin_list"
    )
    critical_severity = models.ManyToManyField(
        PluginList, related_name="critical_plugin_list"
    )

    name = models.CharField(max_length=50, unique=True)
    users = models.ManyToManyField(User, related_name="service_users")
    checks = models.ManyToManyField(BaseCheck)


class CheckResult(models.Model):
    FAILURE, SUCCESS = list(range(2))
    RESULT_CHOICES = ((SUCCESS, "SUCCESS"), (FAILURE, "FAILURE"))

    result = models.SmallIntegerField(choices=RESULT_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)


class AlertSent(models.Model):
    check_obj = models.ForeignKey(BaseCheck, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)


class AbstractCheck(models.Model):
    base_check = GenericRelation(BaseCheck)
    results = models.ManyToManyField(CheckResult)

    class Meta:
        abstract = True

    @staticmethod
    def execute():
        raise NotImplementedError()


class HttpCheck(AbstractCheck):
    site_name = models.CharField(max_length=50, unique=True, default="https://")
    expected_status_code = models.IntegerField()

    def __str__(self):
        return f"{self.site_name}"

    @staticmethod
    def execute():
        pass


class PingCheck(AbstractCheck):
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return f"{self.ip_address}"

    @staticmethod
    def execute():
        pass


class TcpCheck(AbstractCheck):
    ip_address = models.GenericIPAddressField()
    port = models.IntegerField(default=443)

    def __str__(self):
        return f"{self.ip_address}"

    @staticmethod
    def execute():
        pass

templates/add_ping_check.html
{% extends 'base_accounts.html' %}

{% block title %}Add user to notify{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Add Ping Check</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            {{ ping_check_form }}
            {{ base_check_form }}
            <button type="submit" class="btn btn-primary btn-block">Add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'checkerapp:home' %}">Site Checker</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/service_checks.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Service checks</title>
<style>
th, td, h3 {
    text-align: center;
}
</style>
<script>
function blinker(){
    $('.blinking').fadeOut(500);
    $('.blinking').fadeIn(500);
}
setInterval(blinker, 1000);
</script>
{% endblock head %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:home' %}">Service</a></li>
    <li class="breadcrumb-item active">{{service.name}}</li>
{% endblock breadcrumb %}

{% block body %}
<div class="container">
  {% comment %} {% if user.is_authenticated %} {% endcomment %}
    <div class='card pt-3 shadow-sm'>
    <div class="col-12 row">
        {% if request.user.is_superuser %}
            <a href="{% url 'checkerapp:add_http_check' service.pk %}" class="btn">
            <img src='{% static "images/add.png" %}' width=40 height=40/>
            </a>
        {% else %}
            <img class="ml-3 mt-2 disabled" src='{% static "images/not_allowed.png" %}' width=20 height=20/>
        {% endif %}

        {% if not http_checks %}
            <h3 class="text-center col-10">No HTTP Checks Found</h3></div><br>
        {% else %}
            <h3 class="text-center col-10 mt-1 ">HTTP Checks</h3>
    </div>

    <table class="mt-2 table">
        <thead class="thead-inverse">
        <tr>
            <th >PK</th>
            <th >Site Name</th>
            <th >Status</th>
            <th >Time</th>
            <th >Interval</th>
            <th >Back-off Count</th>
            <th >Report</th>
            {% if user.is_superuser %}
                <th >Actions</th>
                <th >Maintenance</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for site in http_checks %}
            <tr>
            <td>{{site.content_object.pk}}</td>
            <td><a href="{% url 'checkerapp:http_info' site.content_object.pk %}">{{site.content_object.site_name}}</a></td>
            {% if site.content_object.results.last.result %}
                <td class="text-success">{{site.content_object.results.last.get_result_display}}</td>
            {% else %}
                <td class="blinking text-danger">{{site.content_object.results.last.get_result_display}}</td>
            {% endif %}
            <td>{{site.content_object.results.last.created_at}}</td>
            <td>{{site.interval}}</td>
            <td>{{site.backoff_count}}</td>
            <td><a href="{% url 'checkerapp:report' site.pk %}">View</a></td>

            {% if user.is_superuser %}
            <td>
                <a href="{% url 'checkerapp:edit_http_check' service.pk site.content_object.pk %}"><img src='{% static "images/edit.png" %}' width=20 height=20/> </a>
                <a href="{% url 'checkerapp:delete_check' site.content_type.id service.pk site.content_object.pk %}"><img src='{% static "images/delete.png" %}' width=20 height=20/> </a>
            </td>
            <td>
                {% if site.maintenance_mode %}
                    <a href="{% url 'checkerapp:maintenance' site.content_type.id service.pk site.content_object.pk  %}">
                    <img src='{% static "images/toggle_on.png" %}' width=40 height=40/>
                    <a>
                    {% comment %} <a class="btn btn-outline-danger" href="{% url 'checkerapp:maintenance' site.content_type.id service.pk site.content_object.pk  %}">Turn on</a> {% endcomment %}
                {% else %}
                    <a href="{% url 'checkerapp:maintenance' site.content_type.id service.pk site.content_object.pk  %}">
                    <img src='{% static "images/toggle_off.png" %}' width=40 height=40/>
                    </a>
                    {% comment %} <a class="btn btn-outline-success" href="{% url 'checkerapp:maintenance' site.content_type.id service.pk site.content_object.pk  %}">Turn off</a> {% endcomment %}
                {% endif %}
            </td>
            </tr>
            {% endif %}
        {% endfor %}
        </tbody>
        {% endif %}
    </table>
    </div>

    <div class='card pt-3 mt-3 shadow-sm'>
    <div class="col-12 row">
        {% if request.user.is_superuser %}
            <a href="{% url 'checkerapp:add_ping_check' service.pk %}" class="btn">
            <img src='{% static "images/add.png" %}' width=40 height=40/>
            </a>
        {% else %}
            <img class="ml-3 mt-2 disabled" src='{% static "images/not_allowed.png" %}' width=20 height=20/>
        {% endif %}

        {% if not ping_checks %}
            <h3 class="text-center col-10">No Ping Checks Found</h3></div><br>
        {% else %}
            <h3 class="text-center col-10 mt-1">Ping Checks</h3>
    </div>
    <table class="mt-2 table">
        <thead class="thead-inverse">
        <tr>
            <th>PK</th>
            <th>IP Address</th>
            <th>Status</th>
            <th>Time</th>
            <th>Interval</th>
            <th>Back-off Count</th>
            <th>Report</th>
            {% if user.is_superuser %}
                <th>Actions</th>
                <th>Maintenance</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for ip_address in ping_checks %}
            <tr>
            <td>{{ip_address.content_object.pk}}</td>
            <td>
                <a href="{% url 'checkerapp:ping_info' ip_address.content_object.pk %}">{{ip_address.content_object.ip_address}}</a>
            </td>
            {% if ip_address.content_object.results.last.result %}
                <td class="text-success">{{ip_address.content_object.results.last.get_result_display}}</td>
            {% else %}
                <td class="blinking text-danger">{{ip_address.content_object.results.last.get_result_display}}</td>
            {% endif %}
            <td>{{ip_address.content_object.results.last.created_at}}</td>
            <td>{{ip_address.interval}}</td>
            <td>{{ip_address.backoff_count}}</td>
            <td><a href="{% url 'checkerapp:report' ip_address.pk %}">View</a></td>

            {% if user.is_superuser %}
            <td >
                <a href="{% url 'checkerapp:edit_ping_check' service.pk ip_address.content_object.pk %}"><img src='{% static "images/edit.png" %}' width=20 height=20/> </a>
                <a href="{% url 'checkerapp:delete_check' ip_address.content_type.id service.pk ip_address.content_object.pk %}"><img src='{% static "images/delete.png" %}' width=20 height=20/> </a>
            </td>
            <td >
                {% if ip_address.maintenance_mode %}
                    <a href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk  %}">
                    <img src='{% static "images/toggle_on.png" %}' width=40 height=40/>
                    {% comment %} <a class="btn btn-outline-danger" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn on</a> {% endcomment %}
                {% else %}
                    </a>
                    <a href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk  %}">
                    <img src='{% static "images/toggle_off.png" %}' width=40 height=40/>
                    </a>
                    {% comment %} <a class="btn btn-outline-success" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn off</a> {% endcomment %}
                {% endif %}
            </td>
            {% endif %}
            </tr>
        {% endfor %}
        {% endif %}
        </tbody>
    </table>
    </div>

    <div class='card pt-3 mt-3 shadow-sm mb-3'>
    <div class="col-12 row">
        {% if request.user.is_superuser %}
            <a href="{% url 'checkerapp:add_tcp_check' service.pk %}" class="btn">
            <img src='{% static "images/add.png" %}' width=40 height=40/>
            </a>
        {% else %}
            <img class="ml-3 mt-2 disabled" src='{% static "images/not_allowed.png" %}' width=20 height=20/>
        {% endif %}

        {% if not tcp_checks %}
            <h3 class="text-center col-10">No TCP Checks Found</h3></div><br>
        {% else %}
            <h3 class="text-center col-10 mt-1">TCP Checks</h3>
    </div>
    <table class="mt-2 table">
        <thead class="thead-inverse">
        <tr>
            <th>PK</th>
            <th>IP Address</th>
            <th>Status</th>
            <th>Time</th>
            <th>Interval</th>
            <th>Back-off Count</th>
            <th>Report</th>
            {% if user.is_superuser %}
                <th>Actions</th>
                <th>Maintenance</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for ip_address in tcp_checks %}
            <tr>
            <td>{{ip_address.content_object.pk}}</td>
            <td>
                <a href="{% url 'checkerapp:tcp_info' ip_address.content_object.pk %}">{{ip_address.content_object.ip_address}}</a>
            </td>
            {% if ip_address.content_object.results.last.result %}
                <td class="text-success">{{ip_address.content_object.results.last.get_result_display}}</td>
            {% else %}
                <td class="blinking text-danger">{{ip_address.content_object.results.last.get_result_display}}</td>
            {% endif %}
            <td>{{ip_address.content_object.results.last.created_at}}</td>
            <td>{{ip_address.interval}}</td>
            <td>{{ip_address.backoff_count}}</td>
            <td><a href="{% url 'checkerapp:report' ip_address.pk %}">View</a></td>

            {% if user.is_superuser %}
            <td >
                <a href="{% url 'checkerapp:edit_tcp_check' service.pk ip_address.content_object.pk %}"><img src='{% static "images/edit.png" %}' width=20 height=20/> </a>
                <a href="{% url 'checkerapp:delete_check' ip_address.content_type.id service.pk ip_address.content_object.pk %}"><img src='{% static "images/delete.png" %}' width=20 height=20/> </a>
            </td>
            <td >
                {% if ip_address.maintenance_mode %}
                    <a href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk  %}">
                    <img src='{% static "images/toggle_on.png" %}' width=40 height=40/>
                    {% comment %} <a class="btn btn-outline-danger" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn on</a> {% endcomment %}
                {% else %}
                    </a>
                    <a href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk  %}">
                    <img src='{% static "images/toggle_off.png" %}' width=40 height=40/>
                    </a>
                    {% comment %} <a class="btn btn-outline-success" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn off</a> {% endcomment %}
                {% endif %}
            </td>
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    {% endif %}
</div>
{% endblock body %}

templates/service_info.html
{% extends 'base.html' %}
{% block head %}
<title>Services</title>
<style>
th, td {
    text-align: center;
}
</style>

{% endblock head %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'checkerapp:home' %}">Services</a></li>
    <li class="breadcrumb-item active">{{service.name}}</li>
{% endblock %}

{% block body %}
  {% if user.is_authenticated %}
    <div class="container">

    {% if not http_checks %}
        <h3 >No Http Checks Found</h3>
    {% else %}
      <div class="col-12 row">
        <a href="{% url 'checkerapp:add_http_check' service.pk %}" class="btn btn-primary text-left ml-3">Add</a>
        <h3 class="text-center col-10">HTTP Checks</h3>
      </div>
      <div class="col-12">
        <table class="mt-2 table">
            <thead class="thead-inverse">
            <tr>
                <th >PK</th>
                <th >Site Name</th>
                <th >Status</th>
                <th >Time</th>
                <th >Interval</th>
                <th >Back-off Count</th>
                <th >Report</th>
                {% if user.is_superuser %}
                <th >Actions</th>
                <th >Maintenance</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for site in http_checks %}
                <tr>
                <td>{{site.content_object.pk}}</td>
                <td><a href="{% url 'checkerapp:http_info' site.content_object.pk %}">{{site.content_object.site_name}}</a></td>
                <td>{{site.content_object.results.last.get_result_display}}</td>
                <td>{{site.created_at}}</td>
                <td>{{site.interval}}</td>
                <td>{{site.backoff_count}}</td>

                <td><a href="{% url 'checkerapp:test' %}">View</a></td>


                {% if user.is_superuser %}
                <td>
                    <a href="{% url 'checkerapp:edit_http_check' service.pk site.content_object.pk %}">Edit</a>
                    <a href="{% url 'checkerapp:delete_check' site.content_type.id service.pk site.content_object.pk %}">Delete</a>
                </td>
                <td>
                    {% if site.maintenance_mode is False %}
                        <a class="btn btn-outline-success" href="{% url 'checkerapp:maintenance' site.content_type.id service.pk site.content_object.pk  %}">Turn off</a>
                    {% else %}
                        <a class="btn btn-outline-danger" href="{% url 'checkerapp:maintenance' site.content_type.id service.pk site.content_object.pk  %}">Turn on</a>
                    {% endif %}
                </td>
                {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    {% if not ping_checks %}
        <h3 >No Ping Checks Found</h3>
    {% else %}
    <div class="col-12">
        <div class="col-12 row">
            <a href="{% url 'checkerapp:add_ping_check' service.pk %}" class="btn btn-primary text-left ml-3">Add</a>
            <h3 class="text-center col-10">Ping Checks</h3>
        </div>
    <div class="col-12">
        <table class="mt-2 table">
            <thead class="thead-inverse">
            <tr>
                <th>PK</th>
                <th>IP Address</th>
                <th>Status</th>
                <th>Time</th>
                <th>Interval</th>
                <th>Backoff Count</th>
                <th>Report</th>
                {% if user.is_superuser %}
                <th>Actions</th>
                <th>Maintenance</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for ip_address in ping_checks %}
                <tr>
                <td>{{ip_address.content_object.pk}}</td>
                <td>
                    <a href="{% url 'checkerapp:ping_info' ip_address.content_object.pk %}">{{ip_address.content_object.ip_address}}</a>
                </td>
                <td>{{ip_address.content_object.results.last.get_result_display}}</td>
                <td>{{ip_address.created_at}}</td>
                <td>{{ip_address.interval}}</td>
                <td>{{ip_address.backoff_count}}</td>
                <td><a href="{% url 'checkerapp:test' %}">View</a></td>

                {% if user.is_superuser %}
                <td >
                    <a href="{% url 'checkerapp:edit_ping_check' service.pk ip_address.content_object.pk %}">Edit</a>
                    <a href="{% url 'checkerapp:delete_check' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Delete</a>
                </td>
                <td >
                    {% if ip_address.maintenance_mode is False %}
                        <a class="btn btn-outline-success" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn off</a>
                    {% else %}
                        <a class="btn btn-outline-danger" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn on</a>
                    {% endif %}
                </td>
                {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    {% if not tcp_checks %}
        <h3 >No Tcp Checks Found</h3>
    {% else %}
    <div class="col-12">
        <div class="col-12 row">
            <a href="{% url 'checkerapp:add_tcp_check' service.pk %}" class="btn btn-primary text-left ml-3">Add</a>
            <h3 class="text-center col-10">TCP Checks</h3>
        </div>
    <div class="col-12">
        <table class="mt-2 table">
            <thead class="thead-inverse">
            <tr>
                <th>PK</th>
                <th>IP Address</th>
                <th>Status</th>
                <th>Time</th>
                <th>Interval</th>
                <th>Backoff Count</th>
                <th>Report</th>
                {% if user.is_superuser %}
                <th>Actions</th>
                <th>Maintenance</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for ip_address in tcp_checks %}
                <tr>
                <td>{{ip_address.content_object.pk}}</td>
                <td>
                    <a href="{% url 'checkerapp:tcp_info' ip_address.content_object.pk %}">{{ip_address.content_object.ip_address}}</a>
                </td>
                <td>{{ip_address.content_object.results.last.get_result_display}}</td>
                <td>{{ip_address.created_at}}</td>
                <td >{{ip_address.interval}}</td>
                <td >{{ip_address.backoff_count}}</td>

                <td><a href="{% url 'checkerapp:test' %}">View</a></td>

                {% if user.is_superuser %}
                <td >
                    <a href="{% url 'checkerapp:edit_tcp_check' service.pk ip_address.content_object.pk %}">Edit</a>
                    <a href="{% url 'checkerapp:delete_check' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Delete</a>
                </td>
                <td >
                    {% if ip_address.maintenance_mode is False %}
                        <a class="btn btn-outline-success" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn off</a>
                    {% else %}
                        <a class="btn btn-outline-danger" href="{% url 'checkerapp:maintenance' ip_address.content_type.id service.pk ip_address.content_object.pk %}">Turn on</a>
                    {% endif %}
                </td>
                {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}


    {% elif not http_checks %}
      <div class="d-flex justify-content-center">
        <h1> Hello there ! </h1>
      </div>
        <h3 class="d-flex justify-content-center">Please create super-user and then <a href="{% url 'accounts:login' %}"> &nbsp Log in !</a> !</h3>

    {% else %}
      <div class="d-flex justify-content-center">
        <h1> Hello there ! </h1>
      </div>
        <h3 class="d-flex justify-content-center">Please<a href="{% url 'accounts:login' %}"> &nbsp Log in !</a> </h3>
    {% endif %}
  </body>
{% endblock body %}